### ISSUE TITLE
demo app crashing on PhotoEditorActivity

### ISSUE THREAD

**Issue by satendra02** [imgly/imgly-sdk-android-demo#22] opened 2016-10-20 05:52 UTC
10-20 11:20:49.317 3548-3548/com.photoeditorsdk.android.app D/AndroidRuntime: Shutting down VM
10-20 11:20:49.318 3548-3548/com.photoeditorsdk.android.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.photoeditorsdk.android.app, PID: 3548
                                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{com.photoeditorsdk.android.app/ly.img.android.ui.activities.PhotoEditorActivity}: android.view.InflateException: Binary XML file line #16: Binary XML file line #16: Error inflating class layout
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                               Caused by: android.view.InflateException: Binary XML file line #16: Binary XML file line #16: Error inflating class layout
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                                  at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393)
                                                                                  at android.app.Activity.setContentView(Activity.java:2166)
                                                                                  at ly.img.android.ui.activities.PhotoEditorActivity.onCreate(PhotoEditorActivity.java:56)
                                                                                  at android.app.Activity.performCreate(Activity.java:6237)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                               Caused by: android.view.InflateException: Binary XML file line #16: Error inflating class layout
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                  at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393) 
                                                                                  at android.app.Activity.setContentView(Activity.java:2166) 
                                                                                  at ly.img.android.ui.activities.PhotoEditorActivity.onCreate(PhotoEditorActivity.java:56) 
                                                                                  at android.app.Activity.performCreate(Activity.java:6237) 
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                               Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.layout" on path: DexPathList[[zip file "/data/app/com.photoeditorsdk.android.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.photoeditorsdk.android.app-1/lib/x86, /data/app/com.photoeditorsdk.android.app-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
                                                                                  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:583)
                                                                                  at android.view.LayoutInflater.onCreateView(LayoutInflater.java:677)
                                                                                  at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:68)
                                                                                  at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694)
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762)
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                  at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393) 
                                                                                  at android.app.Activity.setContentView(Activity.java:2166) 
                                                                                  at ly.img.android.ui.activities.PhotoEditorActivity.onCreate(PhotoEditorActivity.java:56) 
                                                                                  at android.app.Activity.performCreate(Activity.java:6237) 
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                              	Suppressed: java.lang.ClassNotFoundException: Didn't find class "android.view.layout" on path: DexPathList[[dex file "/data/data/com.photoeditorsdk.android.app/files/instant-run/dex/slice-support-annotations-24.2.1_103ce40d8f2857adc81c4095b1007d93ed421f21-classes.dex", dex file "/data/data/com.photoeditorsdk.android.app/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.photoeditorsdk.android.app/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.photoeditorsdk.android.app/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.photoeditorsdk.android.app/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.photoeditorsdk.android.app/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.photoeditorsdk.android.app/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.photoeditorsdk.android.app/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.photoeditorsdk.android.app/files/insta

**Comment by besho** [comment] 2016-10-20 06:57
Yes, Same with me but i fix it by getting imgly_activity_photo_editor.xml from CustomizeLayoutExample and put it inside my layout.

But library still have big issue that after capturing the photo and edited it, it saved in sdcard with name different from the path that returned inActivityResult

**Comment by satendra02** [comment] 2016-10-20 07:11
Thanks **besho** for your quick fix, it saved my day.

**Comment by maltebaumann** [comment] 2016-10-20 10:02
Hi guys and sorry for my delayed response.

The issue is caused by the [Android Data Binding library](https://developer.android.com/topic/libraries/data-binding/index.html), which we use in the new 2.0.11 version. To fix the crash you need to add the following lines to your apps `build.gradle`:

```
android {
    [...]
    dataBinding {
        enabled = true
    }
}
```

I'll update the demo app and documentation and close this issue afterwards.

Thanks for your help and patience!

**Closed** 2016-10-20 10:06 UTC
