### ISSUE TITLE
My App icon changed after integrating sdk

### ISSUE THREAD

**Issue by ankurchitranshi** [imgly/imgly-sdk-android-demo#7] opened 2016-06-02 06:59 UTC
when i integrated this library , then the app icon changed to library's icon , if this is default functionality, then how can i remove this as i don't want to use library's default icon.

**Comment by sascha** [comment] 2016-06-02 09:26
@ankurchitranshi This shouldn't happen. Did you integrate the SDK as described in the documentation? I'm unable to reproduce the issue, but it may have been fixed in https://github.com/imgly/imgly-sdk-android/commit/23cc677b482d94e98ca86150a6e8096f98f963af

**Comment by ankurchitranshi** [comment] 2016-06-02 11:08
@sascha Thanks for reply, :)   I followed every step as described, but the issue is there , and one more thing the link you posted, is not working.

**Comment by ankurchitranshi** [comment] 2016-06-03 12:05
@sascha I sorted out the problem , I changed my app's app icon name

**Closed** 2016-06-08 14:00 UTC
