### ISSUE TITLE
Black Screen Issue

### ISSUE THREAD

**Issue by chiragshenoy** [imgly/imgly-sdk-android-demo#46] opened 2016-12-15 13:12 UTC
Sometimes when I call 

` new CameraPreviewBuilder(this)
                    .setSettingsList(settingsList)
                    .startActivityForResult(this, CAMERA_PREVIEW_RESULT);`

as shown in the demo app , I get a black screen and I'm unable to click a picture. On clicking the "capture image" button, the button animates and nothing else happens.

I'm able to reproduce this bug consistently.

May we know what may be the issue ?

**Comment by svendvd** [comment] 2017-01-04 12:55
We are currently working on this Problem.

**Comment by svendvd** [comment] 2017-02-23 18:47
Sorry for the long delay but this was no easy issue and only on some devices (not reproducible on our test devices). 
We have found an issue with the OpenGl implementation in the Camera Preview.

Please try `ly.img.android:photo-editor-sdk:3.0.5-beta` and let us know it the problem is gone.

**Comment by svendvd** [comment] 2017-03-01 10:17
Released with v3.0.6

**Closed by svendvd** 2017-03-01 10:17 UTC
